"""Reporting & evidence builders extracted from agents.py.

Live evidence snapshot, markdown + PDF evidence pack, auditor Q&A trail,
board-evidence digest, runtime playbook templates, and the branded
auditor-room PDF watermark. Import-light (no router) so agents.py stays
route-focused. One-way dependency: agents.py -> agent_reports (the two
agent-logic helpers used by _evidence_snapshot are lazily imported back).
"""
from db import db


async def _evidence_snapshot(org_id):
    from datetime import datetime, timezone
    from bson import ObjectId
    from agents import _tool_violations, _is_toxic
    org = await db.organizations.find_one(
        {"_id": ObjectId(org_id)}, {"name": 1, "agent_runtime_webhook": 1, "agent_runtime_webhook_secret": 1}) or {}
    agents = await db.ai_agents.find({"org_id": org_id}, {"_id": 0}).to_list(500)
    events = await db.agent_enforcements.find({"org_id": org_id}, {"_id": 0}).sort("at", -1).to_list(1000)
    for a in agents:
        a["tool_violations"] = _tool_violations(a)
        a["toxic"] = _is_toxic(a)
    signed = "HMAC-signed" if org.get("agent_runtime_webhook_secret") else "unsigned"
    connector = f"connected ({signed})" if org.get("agent_runtime_webhook") else "control-plane only"
    return {"org_name": org.get("name"), "connector": connector,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "agents": agents, "events": events,
            "counts": {"agents": len(agents), "toxic": sum(1 for a in agents if a["toxic"]),
                       "killed": sum(1 for a in agents if a.get("status") == "killed"),
                       "restricted": sum(1 for a in agents if a.get("status") == "restricted"),
                       "events": len(events)}}


def _evidence_markdown(snap):
    c = snap.get("counts", {})
    lines = [
        "## Attestation",
        f"Generated by Obserra — Agentic AI Security Control Plane for {snap.get('org_name') or 'the organization'} "
        f"on {snap.get('generated_at')}. Runtime connector: {snap.get('connector')}. Every enforcement below "
        "carries a runtime receipt.", "",
        "## AI Agent Toxicity Snapshot",
        f"{c.get('agents', 0)} governed agent(s) · {c.get('toxic', 0)} toxic · {c.get('killed', 0)} killed · "
        f"{c.get('restricted', 0)} restricted.", ""]
    for a in snap.get("agents", []):
        tv = a.get("tool_violations") or []
        lines.append(f"## {a.get('name')} ({a.get('ref')})")
        lines += [f"Status: {a.get('status')} · authority: {a.get('authority', '—')}",
                  "Toxic combination: " + (("YES — " + ", ".join(tv)) if tv else "none detected"), ""]
    lines += ["## Runtime Enforcement Audit Trail", f"{c.get('events', 0)} enforcement event(s) recorded.", ""]
    for e in snap.get("events", []):
        rc = e.get("receipt") or {}
        runtime = ("runtime OK" if e.get("external_ok") else
                   ("runtime UNREACHABLE" if e.get("runtime") == "external-webhook" else "control-plane"))
        lines.append(f"## {e.get('name') or e.get('ref')} — {(e.get('verb') or e.get('action') or '').upper()}")
        lines += [f"When: {e.get('at')} · by {e.get('by')} · via {e.get('source')}",
                  "Receipt: " + runtime + (f" · HTTP {rc.get('status_code')} · {rc.get('latency_ms')}ms · "
                  f"{rc.get('attempts')} attempt(s) · {'signed' if rc.get('signed') else 'unsigned'}" if rc else ""), ""]
    return "\n".join(lines)



# ── Shared evidence-PDF builder + Q&A markdown ────────────────────────────────
def _evidence_pdf(snap, extra_md: str = ""):
    from reports import _build_pdf
    c = snap.get("counts", {})
    md = _evidence_markdown(snap)
    if extra_md:
        md += "\n" + extra_md
    return _build_pdf(md, "AI Enforcement Evidence Pack", cover=True, org_name=snap.get("org_name"),
                      exec_summary=f"{c.get('agents', 0)} governed agents, {c.get('toxic', 0)} toxic; "
                                   f"{c.get('events', 0)} runtime enforcement actions with verifiable receipts.")


def _qa_markdown(qa):
    if not qa:
        return ""
    lines = ["## Auditor Q&A Trail", f"{len(qa)} auditor question(s) recorded.", ""]
    for q in qa:
        lines.append(f"## Q from {q.get('author') or 'Auditor'} — {q.get('status') or 'Open'}")
        msgs = q.get("messages") or (
            [{"role": "auditor", "by": q.get("author"), "text": q.get("text"), "at": q.get("at")}]
            + ([{"role": "admin", "text": q.get("reply"), "at": q.get("reply_at")}] if q.get("reply") else []))
        for m in msgs:
            who = "Auditor" if m.get("role") == "auditor" else "Governance"
            att = " [signed evidence pack attached]" if m.get("attachment") else ""
            lines.append(f"{who} ({(m.get('at') or '')[:16]}): {m.get('text') or ''}{att}")
        lines.append("")
    return "\n".join(lines)



# ── Board digest builder (shared by send + preview) + preview / access-log endpoints ──
async def _build_board_digest(org):
    import base64
    from datetime import datetime, timezone, timedelta
    now = datetime.now(timezone.utc)
    oid = str(org["_id"])
    since = (now - timedelta(days=30)).isoformat()
    events = await db.agent_enforcements.find({"org_id": oid, "at": {"$gte": since}}, {"_id": 0}).to_list(2000)
    kills = sum(1 for e in events if e.get("action") == "kill")
    suspends = sum(1 for e in events if e.get("action") == "suspend")
    resumes = sum(1 for e in events if e.get("action") == "resume")
    snap = await _evidence_snapshot(oid)
    c = snap.get("counts", {})
    systems = await db.ai_systems.find({"org_id": oid}, {"_id": 0}).to_list(500)
    sanctioned_sys = sum(1 for s in systems if s.get("status") == "sanctioned")
    shadow_sys = sum(1 for s in systems if s.get("status") == "shadow")
    qa = await db.evidence_room_comments.find({"org_id": oid}, {"_id": 0}).sort("at", 1).to_list(500)
    open_qs = sum(1 for q in qa if q.get("status") != "Resolved")
    pdf_bytes = _evidence_pdf(snap, _qa_markdown(qa)).getvalue()
    att = [{"filename": "obserra-ai-enforcement-evidence.pdf", "content": base64.b64encode(pdf_bytes).decode()}]
    oname = org.get("name") or "your organization"

    def row(k, v, col):
        return (f"<tr><td style='padding:8px 12px;border-bottom:1px solid #eef2f7;font:600 13px Arial;color:#374151'>{k}</td>"
                f"<td style='padding:8px 12px;border-bottom:1px solid #eef2f7;font:800 15px Arial;color:{col};text-align:right'>{v}</td></tr>")

    html = (f"<div style='font:400 14px Arial;color:#1f2937;max-width:600px;margin:auto'>"
            f"<h2 style='color:#0f1e3d;margin-bottom:2px'>AI Security — Board Evidence Digest</h2>"
            f"<div style='font:400 12px Arial;color:#6b7280;margin-bottom:14px'>{oname} · last 30 days · {now.strftime('%B %Y')}</div>"
            f"<table width='100%' cellspacing='0' cellpadding='0' style='border:1px solid #eef2f7;border-radius:10px;overflow:hidden'>"
            f"{row('Agents killed', kills, '#dc2626')}"
            f"{row('Agents suspended', suspends, '#d97706')}"
            f"{row('Agents resumed', resumes, '#16a34a')}"
            f"{row('Toxic agents (current)', c.get('toxic', 0), '#dc2626')}"
            f"{row('Governed agents', c.get('agents', 0), '#0f1e3d')}"
            f"{row('Sanctioned AI systems', sanctioned_sys, '#16a34a')}"
            f"{row('Shadow AI systems', shadow_sys, '#dc2626')}"
            f"{row('Auditor questions (open / total)', f'{open_qs} / {len(qa)}', '#0f1e3d')}"
            f"</table>"
            f"<p style='font:400 13px Arial;color:#374151;margin-top:14px'>The full, signed AI Enforcement Evidence Pack — with every runtime enforcement receipt, the live toxicity snapshot and the complete auditor Q&amp;A trail — is attached as a PDF for the board / audit committee.</p>"
            f"<p style='font-size:11px;color:#9ca3af'>Obserra — Agentic AI Security Control Plane · Defensibility Ledger</p></div>")
    cfg = org.get("board_digest_recipients") or []
    if cfg:
        recips = [{"email": e} for e in cfg]
    else:
        recips = await db.users.find({"org_id": oid, "role": {"$in": ["admin", "executive"]}}, {"_id": 0, "email": 1}).to_list(200)
    counts = {"kills": kills, "suspends": suspends, "resumes": resumes, "toxic": c.get("toxic", 0),
              "agents": c.get("agents", 0), "sanctioned_systems": sanctioned_sys, "shadow_systems": shadow_sys,
              "questions_open": open_qs, "questions_total": len(qa)}
    return {"html": html, "subject": f"AI Security — Board Evidence Digest ({now.strftime('%b %Y')})",
            "att": att, "pdf_bytes": pdf_bytes, "recips": recips, "counts": counts,
            "nothing": (kills + suspends + resumes) == 0 and c.get("toxic", 0) == 0,
            "summary": f"{kills} kills · {suspends} suspends · {c.get('toxic', 0)} toxic agents (30d) — emailed with the signed PDF + Q&A trail."}



# ── Runtime enforcement playbooks — per-provider webhook templates (reference) ──
_RUNTIME_PLAYBOOKS = [
    {"id": "generic", "name": "Generic HTTP runtime",
     "blurb": "Any orchestrator with an HTTP control endpoint. Obserra POSTs a signed JSON body; your adapter maps the action to your stop/pause/resume call.",
     "map": {"suspend": "pause the agent / revoke its execution token", "kill": "terminate the agent + revoke credentials", "resume": "re-enable the agent"},
     "docs": "https://obserra.ai/docs/runtime-webhook",
     "example": "if body['action']=='kill': runtime.terminate(body['agent_ref'])\nelif body['action']=='suspend': runtime.pause(body['agent_ref'])\nelif body['action']=='resume': runtime.resume(body['agent_ref'])"},
    {"id": "langgraph", "name": "LangGraph / LangServe",
     "blurb": "Map Obserra actions to LangGraph thread/run controls. Kill cancels the run and disables the assistant; suspend interrupts the thread.",
     "map": {"suspend": "client.threads.update(thread_id, metadata={'obserra':'suspended'}) + interrupt", "kill": "client.runs.cancel(thread_id, run_id) + disable assistant", "resume": "clear the interrupt / re-enable assistant"},
     "docs": "https://langchain-ai.github.io/langgraph/cloud/reference/api/",
     "example": "action=body['action']\nif action=='kill': client.runs.cancel(thread_id, run_id); client.assistants.delete(assistant_id)\nif action=='suspend': client.threads.update(thread_id, metadata={'status':'suspended'})\nif action=='resume': client.threads.update(thread_id, metadata={'status':'active'})"},
    {"id": "crewai", "name": "CrewAI",
     "blurb": "Gate crew kickoff on Obserra state. Kill removes the agent from the crew roster; suspend flips a shared kill-switch the crew checks before each task.",
     "map": {"suspend": "set crew.state['obserra_suspended']=True (checked in a before_kickoff hook)", "kill": "remove the agent from crew.agents and persist a blocklist", "resume": "clear the suspended flag"},
     "docs": "https://docs.crewai.com/",
     "example": "@before_kickoff\ndef gate(inputs):\n    st = load_obserra_state(inputs['agent_ref'])\n    if st in ('suspend','kill'): raise RuntimeError('Blocked by Obserra')"},
    {"id": "bedrock", "name": "AWS Bedrock Agents",
     "blurb": "Map to Bedrock Agent lifecycle. Kill disables the agent alias (or deletes it); suspend routes invocations to a deny action group.",
     "map": {"suspend": "attach a deny guardrail / disable the working alias", "kill": "DeleteAgentAlias or PrepareAgent with a blocked action group", "resume": "restore the alias"},
     "docs": "https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_Operations_Agents_for_Amazon_Bedrock.html",
     "example": "import boto3\nc=boto3.client('bedrock-agent')\nif action=='kill': c.delete_agent_alias(agentId=aid, agentAliasId=alias)\nif action=='suspend': c.update_agent_alias(agentId=aid, agentAliasId=alias, routingConfiguration=[])"},
]



async def _brand_watermark_pdf(pdf_bytes: bytes, org_id=None, room_url: str = "", subtext: str = "") -> bytes:
    """Per-page provenance overlay: faint 'AUDITOR ROOM COPY', org logo, a QR linking back to the live
    room, and the downloader stamp. Fails open — returns the original bytes on any error."""
    try:
        import os as _os
        from io import BytesIO
        from bson import ObjectId
        from pypdf import PdfReader, PdfWriter
        from reportlab.pdfgen import canvas
        from reportlab.lib import colors
        from reportlab.graphics.barcode.qr import QrCodeWidget
        from reportlab.graphics.shapes import Drawing
        from reportlab.graphics import renderPDF
        badge = None
        try:
            from reports import _resolve_brand
            org = await db.organizations.find_one({"_id": ObjectId(org_id)}) if org_id else None
            brand = _resolve_brand(org)
            if brand.get("badge") and _os.path.exists(brand["badge"]):
                badge = brand["badge"]
        except Exception:
            badge = None
        reader = PdfReader(BytesIO(pdf_bytes))
        writer = PdfWriter()
        for page in reader.pages:
            w = float(page.mediabox.width); h = float(page.mediabox.height)
            buf = BytesIO()
            c = canvas.Canvas(buf, pagesize=(w, h))
            c.saveState(); c.translate(w / 2, h / 2); c.rotate(38)
            c.setFillColor(colors.Color(0.55, 0.6, 0.72, alpha=0.12))
            c.setFont("Helvetica-Bold", 52); c.drawCentredString(0, 18, "AUDITOR ROOM COPY")
            c.restoreState()
            if room_url:
                try:
                    qw = QrCodeWidget(room_url); b = qw.getBounds()
                    size = 52
                    d = Drawing(size, size, transform=[size / (b[2] - b[0]), 0, 0, size / (b[3] - b[1]), 0, 0])
                    d.add(qw)
                    renderPDF.draw(d, c, w - size - 22, 20)
                    c.setFont("Helvetica", 6); c.setFillColor(colors.Color(0.42, 0.47, 0.57))
                    c.drawCentredString(w - size / 2 - 22, 14, "scan for live room")
                except Exception:
                    pass
            if badge:
                try:
                    c.drawImage(badge, 22, 18, width=40, height=40, mask="auto", preserveAspectRatio=True, anchor="sw")
                except Exception:
                    pass
            if subtext:
                c.setFont("Helvetica", 8); c.setFillColor(colors.Color(0.42, 0.47, 0.57))
                c.drawString(70, 30, subtext)
            c.save(); buf.seek(0)
            page.merge_page(PdfReader(buf).pages[0])
            try:
                page.compress_content_streams()
            except Exception:
                pass
            writer.add_page(page)
        out = BytesIO(); writer.write(out)
        return out.getvalue()
    except Exception:
        return pdf_bytes



# ── Auditor-question per-priority SLA + on-call rotation + integrity + weekly digest ──
import hashlib as _hashlib
import json as _json


def _canonical_snapshot_hash(snap) -> str:
    """Stable SHA-256 over the canonical evidence snapshot (order-independent)."""
    try:
        blob = _json.dumps(snap or {}, sort_keys=True, default=str, separators=(",", ":"))
    except Exception:
        blob = str(snap)
    return _hashlib.sha256(blob.encode("utf-8")).hexdigest()


def _sla_for(org, priority="normal") -> int:
    """Per-priority auditor-question SLA (hours). 'normal' falls back to the org base SLA."""
    try:
        base = int((org or {}).get("auditor_question_sla_hours") or 48)
    except Exception:
        base = 48
    defaults = {"urgent": 4, "high": 12, "normal": base, "low": 96}
    sbp = (org or {}).get("auditor_question_sla_by_priority") or {}
    p = (priority or "normal").lower()
    try:
        return max(1, min(4320, int(sbp.get(p) or defaults.get(p, base))))
    except Exception:
        return defaults.get(p, base)


def _escalation_hours_for(org, priority="normal") -> float:
    """Escalation threshold = per-priority SLA × the org multiplier (default 2×)."""
    try:
        mult = float((org or {}).get("auditor_question_escalation_multiplier") or 2)
    except Exception:
        mult = 2.0
    return _sla_for(org, priority) * max(1.0, mult)


def _oncall_recipient(org) -> str:
    """The weekly on-call approver from the rotation (rotates by ISO week). '' when none set."""
    rot = [e for e in ((org or {}).get("auditor_oncall_rotation") or []) if e and "@" in e]
    if not rot:
        return ""
    from datetime import datetime, timezone
    wk = datetime.now(timezone.utc).isocalendar()[1]
    return rot[wk % len(rot)]


def _stamp_verified_seal(pdf_bytes: bytes, seal_hash: str = "") -> bytes:
    """Overlay a 'Verified by Obserra' integrity seal (short SHA-256) on page 1. Fails open."""
    if not seal_hash:
        return pdf_bytes
    try:
        from io import BytesIO
        from pypdf import PdfReader, PdfWriter
        from reportlab.pdfgen import canvas
        from reportlab.lib import colors
        reader = PdfReader(BytesIO(pdf_bytes))
        writer = PdfWriter()
        for i, page in enumerate(reader.pages):
            if i == 0:
                w = float(page.mediabox.width); h = float(page.mediabox.height)
                buf = BytesIO()
                c = canvas.Canvas(buf, pagesize=(w, h))
                sx, sy, sw, sh = w - 224, h - 60, 204, 38
                c.setFillColor(colors.Color(0.06, 0.5, 0.34, alpha=0.10))
                c.roundRect(sx, sy, sw, sh, 7, fill=1, stroke=0)
                c.setStrokeColor(colors.Color(0.06, 0.5, 0.34, alpha=0.6)); c.setLineWidth(0.9)
                c.roundRect(sx, sy, sw, sh, 7, fill=0, stroke=1)
                c.setFillColor(colors.Color(0.05, 0.4, 0.28))
                c.setFont("Helvetica-Bold", 10); c.drawString(sx + 12, sy + 21, "\u2713 VERIFIED BY OBSERRA")
                c.setFont("Helvetica", 7); c.setFillColor(colors.Color(0.32, 0.42, 0.37))
                c.drawString(sx + 12, sy + 9, f"integrity SHA-256 \u00b7 {seal_hash[:16]}")
                c.save(); buf.seek(0)
                page.merge_page(PdfReader(buf).pages[0])
            writer.add_page(page)
        out = BytesIO(); writer.write(out)
        return out.getvalue()
    except Exception:
        return pdf_bytes


async def _run_auditor_room_weekly_digest():
    """Weekly opt-in summary emailed to auditors who subscribed on a room's public portal — new
    evidence (enforcements) + new/answered questions in the last 7 days. Skips rooms with nothing new."""
    import os
    from datetime import datetime, timezone, timedelta
    from kernel import notifications
    now = datetime.now(timezone.utc)
    since = (now - timedelta(days=7)).isoformat()
    frontend = os.environ.get("FRONTEND_URL", "").rstrip("/")
    rooms = await db.evidence_rooms.find(
        {"digest_subscribers": {"$exists": True, "$ne": []}}, {"_id": 0}).to_list(2000)
    for room in rooms:
        try:
            subs = [e for e in (room.get("digest_subscribers") or []) if e and "@" in e]
            if not subs:
                continue
            if room.get("expires_at") and now.isoformat() > room["expires_at"]:
                continue
            token = room["token"]; oid = room["org_id"]
            new_events = await db.agent_enforcements.count_documents({"org_id": oid, "at": {"$gte": since}})
            new_q = await db.evidence_room_comments.count_documents({"token": token, "at": {"$gte": since}})
            answered = await db.evidence_room_comments.count_documents({"token": token, "reply_at": {"$gte": since}})
            if not (new_events or new_q or answered):
                continue
            room_url = f"{frontend}/audit-room/{token}"
            oname = (room.get("snapshot", {}) or {}).get("org_name") or "the organization"

            def _row(k, v):
                return (f"<tr><td style='padding:7px 12px;border-bottom:1px solid #eef2f7;font:600 13px Arial;color:#374151'>{k}</td>"
                        f"<td style='padding:7px 12px;border-bottom:1px solid #eef2f7;font:800 15px Arial;color:#0f1e3d;text-align:right'>{v}</td></tr>")
            html = (f"<div style='font:400 14px Arial;color:#1f2937;max-width:560px;margin:auto'>"
                    f"<h2 style='color:#0f1e3d;margin-bottom:2px'>Your Obserra auditor room — weekly summary</h2>"
                    f"<div style='font:400 12px Arial;color:#6b7280;margin-bottom:14px'>{oname} · last 7 days · {now.strftime('%B %d, %Y')}</div>"
                    f"<table width='100%' cellspacing='0' cellpadding='0' style='border:1px solid #eef2f7;border-radius:10px;overflow:hidden'>"
                    f"{_row('New enforcement actions', new_events)}"
                    f"{_row('New questions', new_q)}"
                    f"{_row('Answered questions', answered)}"
                    f"</table>"
                    f"<p style='margin:18px 0'><a href='{room_url}' style='background:#12b4d6;color:#04121a;text-decoration:none;padding:11px 18px;border-radius:8px;font-weight:700' target='_blank'>Open the auditor room</a></p>"
                    f"<p style='font-size:11px;color:#9ca3af'>You subscribed to weekly updates for this read-only auditor room. Obserra — Agentic AI Security Control Plane.</p></div>")
            for em in subs:
                try:
                    await notifications.send_email(em, "Your Obserra auditor room — weekly summary", html)
                except Exception:
                    pass
            await db.evidence_rooms.update_one({"token": token}, {"$set": {"digest_last_sent": now.isoformat()}})
        except Exception:
            pass
