"""Iter145 — Cyber Crisis Commander extensions:
   (1) Connector Test Ping, (2) SITREP Preview + note + send-now,
   (3) Director Digest, (4) Connector-Quiet alert.
"""
import asyncio
import os
import sys
import time
from datetime import datetime, timedelta, timezone

import pytest
import requests

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "").rstrip("/")
if not BASE_URL:
    for line in open("/app/frontend/.env"):
        if line.startswith("REACT_APP_BACKEND_URL="):
            BASE_URL = line.split("=", 1)[1].strip().rstrip("/")
            break

ADMIN_EMAIL = "jblan2026@gmail.com"
ADMIN_PASSWORD = "Obserra2026!"


@pytest.fixture(scope="module")
def sess():
    s = requests.Session()
    s.headers.update({"Content-Type": "application/json"})
    r = s.post(f"{BASE_URL}/api/auth/login",
               json={"email": ADMIN_EMAIL, "password": ADMIN_PASSWORD}, timeout=20)
    assert r.status_code == 200, f"login failed: {r.status_code} {r.text[:200]}"
    return s


# ==========================
# FEATURE 1 — Connector Test Ping
# ==========================
class TestConnectorTestPing:
    def test_ping_crowdstrike_updates_health_no_case(self, sess):
        # Snapshot case refs + baseline health
        def _refs():
            body = sess.get(f"{BASE_URL}/api/crisis/cases", timeout=15).json()
            arr = body.get("cases", body) if isinstance(body, dict) else body
            return {c.get("ref") for c in (arr or []) if c.get("ref")}
        before = _refs()
        h0 = sess.get(f"{BASE_URL}/api/crisis/connectors/native", timeout=15).json()
        base = next((c for c in h0["connectors"] if c["vendor"] == "crowdstrike"), {})
        base_count = int(base.get("count") or 0)

        r = sess.post(f"{BASE_URL}/api/crisis/connectors/crowdstrike/test", timeout=15)
        assert r.status_code == 200, f"{r.status_code} {r.text[:200]}"
        body = r.json()
        assert body.get("ok") is True
        assert body.get("vendor") == "crowdstrike"
        assert "mapped" in body and isinstance(body["mapped"], dict)

        # health updated
        h1 = sess.get(f"{BASE_URL}/api/crisis/connectors/native", timeout=15).json()
        after = next((c for c in h1["connectors"] if c["vendor"] == "crowdstrike"), {})
        assert after.get("last_received"), "last_received not set after test ping"
        assert int(after.get("count") or 0) >= base_count + 1

        # no new crisis case attributable to the test ping.
        # (Filter out any TEST_ITER145 cases that other parallel tests may create.)
        after_refs = _refs()
        new_refs = after_refs - before
        if new_refs:
            # Anything newly created must not have been generated by the test ping.
            for ref in new_refs:
                c = sess.get(f"{BASE_URL}/api/crisis/cases/{ref}", timeout=10).json()
                title = ((c.get("case") or c).get("title") or "")
                assert "connection test" not in title.lower() and "obserra connection" not in title.lower(), (
                    f"connector test appears to have created a case: {ref} / {title}")

    def test_ping_all_vendors_ok(self, sess):
        for v in ("splunk", "sentinel", "servicenow", "generic"):
            r = sess.post(f"{BASE_URL}/api/crisis/connectors/{v}/test", timeout=15)
            assert r.status_code == 200, f"{v} -> {r.status_code}"
            assert r.json().get("ok") is True


# ==========================
# FEATURE 2 — SITREP Preview / Note / Send-now
# ==========================
class TestSitrepConsole:
    def test_preview_and_note_persist(self, sess):
        r = sess.post(f"{BASE_URL}/api/crisis/cases",
                      json={"title": "TEST_ITER145 sitrep console",
                            "severity": "Low", "summary": "TEST_ITER145"}, timeout=15)
        assert r.status_code == 200
        ref = r.json()["ref"]
        try:
            p0 = sess.get(f"{BASE_URL}/api/crisis/cases/{ref}/sitrep/preview", timeout=15)
            assert p0.status_code == 200
            b0 = p0.json()
            for k in ("title", "text", "note", "cadence_hours"):
                assert k in b0, f"missing key {k} in preview"
            assert b0["note"] == ""

            # patch a note
            note = "TEST_ITER145 · exec team standby at 15:00 UTC"
            rp = sess.patch(f"{BASE_URL}/api/crisis/cases/{ref}",
                            json={"sitrep_note": note}, timeout=15)
            assert rp.status_code == 200

            p1 = sess.get(f"{BASE_URL}/api/crisis/cases/{ref}/sitrep/preview", timeout=15).json()
            assert p1["note"] == note
            assert note in p1["text"], "note should appear in composed preview text"
        finally:
            _delete_case_via_mongo(ref)

    def test_send_now_posts_and_writes_timeline(self, sess):
        """Monkey-patch self_scan._post_chat_alert BEFORE calling the endpoint.
        The endpoint imports the symbol inside the function via
        `from self_scan import _post_chat_alert`, so patching the module attr works.
        """
        # Load backend .env before import
        for line in open("/app/backend/.env"):
            if "=" in line and not line.strip().startswith("#"):
                k, _, v = line.strip().partition("=")
                os.environ.setdefault(k, v.strip().strip('"').strip("'"))
        sys.path.insert(0, "/app/backend")
        import self_scan as _ss
        original = _ss._post_chat_alert
        calls = {"n": 0}

        async def _no_op(oid, title, text):
            calls["n"] += 1
            return None
        _ss._post_chat_alert = _no_op
        try:
            r = sess.post(f"{BASE_URL}/api/crisis/cases",
                          json={"title": "TEST_ITER145 sitrep send-now",
                                "severity": "Low", "summary": "TEST_ITER145"}, timeout=15)
            ref = r.json()["ref"]
            try:
                sess.patch(f"{BASE_URL}/api/crisis/cases/{ref}",
                           json={"sitrep_note": "TEST_ITER145 note"}, timeout=15)
                rs = sess.post(f"{BASE_URL}/api/crisis/cases/{ref}/sitrep/send-now", timeout=20)
                assert rs.status_code == 200, f"{rs.status_code} {rs.text[:200]}"
                body = rs.json()
                assert "posted" in body
                assert "teams" in body and "slack" in body

                # timeline event 'Manual SITREP sent to leadership chat'
                time.sleep(0.5)
                tl = sess.get(f"{BASE_URL}/api/crisis/cases/{ref}/timeline", timeout=15).json()
                events = tl.get("events") if isinstance(tl, dict) else tl
                manual = [e for e in (events or [])
                          if "Manual SITREP sent to leadership chat" in (e.get("title") or "")]
                assert len(manual) >= 1, "expected Manual SITREP timeline event"
            finally:
                _delete_case_via_mongo(ref)
        finally:
            _ss._post_chat_alert = original


# ==========================
# FEATURE 3 — Director Digest
# ==========================
class TestDirectorDigest:
    def test_settings_toggle_persists(self, sess):
        # Read
        s0 = sess.get(f"{BASE_URL}/api/crisis/settings", timeout=15)
        assert s0.status_code == 200
        b0 = s0.json()
        for k in ("director_digest", "connector_quiet", "connector_quiet_hours"):
            assert k in b0

        # toggle ON
        r_on = sess.post(f"{BASE_URL}/api/crisis/settings",
                         json={"director_digest": True}, timeout=15)
        assert r_on.status_code == 200
        assert r_on.json()["director_digest"] is True

        # toggle OFF (cleanup)
        r_off = sess.post(f"{BASE_URL}/api/crisis/settings",
                         json={"director_digest": False}, timeout=15)
        assert r_off.status_code == 200
        assert r_off.json()["director_digest"] is False

    def test_send_now_no_open_returns_zero(self, sess):
        """If there are open cases we can't safely call the live endpoint (real emails).
        Instead we exercise _build_director_digest directly via in-process import,
        which returns (html, n) with n=0 when there are no non-demo open cases."""
        sys.path.insert(0, "/app/backend")
        for line in open("/app/backend/.env"):
            if "=" in line and not line.strip().startswith("#"):
                k, _, v = line.strip().partition("=")
                os.environ.setdefault(k, v.strip().strip('"').strip("'"))
        import importlib
        cc = importlib.import_module("crisis_commander")
        org_id = _org_id_for_email(ADMIN_EMAIL)
        # It's fine if org has open cases — we just assert the tuple shape + digest structure
        html, n = _shared_loop().run_until_complete(cc._build_director_digest(org_id))
        assert isinstance(n, int)
        if n == 0:
            assert html is None
        else:
            assert isinstance(html, str) and "Weekly Crisis Digest" in html
            assert "OBSERRA · CYBER CRISIS COMMANDER" in html

    def test_run_weekly_only_for_opt_in_orgs(self, sess):
        """Ensure toggle off means the weekly job sends nothing for the org.
        Motor holds a module-global executor bound to the first asyncio loop it
        sees, so we reuse a single loop across all in-process cc.* invocations."""
        sess.post(f"{BASE_URL}/api/crisis/settings",
                  json={"director_digest": False}, timeout=15)
        sys.path.insert(0, "/app/backend")
        for line in open("/app/backend/.env"):
            if "=" in line and not line.strip().startswith("#"):
                k, _, v = line.strip().partition("=")
                os.environ.setdefault(k, v.strip().strip('"').strip("'"))
        import importlib
        cc = importlib.import_module("crisis_commander")
        org_id = _org_id_for_email(ADMIN_EMAIL)
        loop = _shared_loop()
        sent = loop.run_until_complete(cc.run_weekly_director_digest(org_id=org_id))
        assert sent == 0, "digest should NOT be sent when toggle is off"


# ==========================
# FEATURE 4 — Connector-Quiet alert
# ==========================
class TestConnectorQuiet:
    def test_quiet_check_endpoint_shape(self, sess):
        r = sess.get(f"{BASE_URL}/api/crisis/connectors/quiet-check", timeout=15)
        assert r.status_code == 200
        b = r.json()
        for k in ("threshold_hours", "business_hours", "enabled", "quiet"):
            assert k in b
        assert isinstance(b["quiet"], list)
        assert isinstance(b["business_hours"], bool)

    def test_backdate_connector_and_scan_flags(self, sess):
        """Backdate a connector's last_received far in the past, then confirm the
        quiet scan reports it. Uses the quiet-check endpoint (post=False), so no
        live chat post is triggered."""
        # Ensure toggle on for the visibility of 'enabled' field (scan works regardless)
        sess.post(f"{BASE_URL}/api/crisis/settings",
                  json={"connector_quiet": True, "connector_quiet_hours": 6}, timeout=15)
        try:
            org_id = _org_id_for_email(ADMIN_EMAIL)
            assert org_id
            db = _mongo_db()
            # Ensure crowdstrike row exists (test ping above will have created it)
            sess.post(f"{BASE_URL}/api/crisis/connectors/crowdstrike/test", timeout=15)
            far_past = (datetime.now(timezone.utc) - timedelta(hours=48)).isoformat()
            res = db.crisis_connector_health.update_one(
                {"org_id": org_id, "vendor": "crowdstrike"},
                {"$set": {"last_received": far_past, "quiet_alerted_at": None}})
            assert res.matched_count == 1

            qc = sess.get(f"{BASE_URL}/api/crisis/connectors/quiet-check", timeout=15).json()
            assert qc["enabled"] is True
            vendors = [q["vendor"] for q in qc["quiet"]]
            assert "crowdstrike" in vendors, f"expected crowdstrike flagged quiet, got {qc}"

            # Fresh ingest via test ping should clear quiet_alerted_at
            # First set quiet_alerted_at to simulate already-alerted
            db.crisis_connector_health.update_one(
                {"org_id": org_id, "vendor": "crowdstrike"},
                {"$set": {"quiet_alerted_at": datetime.now(timezone.utc).isoformat()}})
            sess.post(f"{BASE_URL}/api/crisis/connectors/crowdstrike/test", timeout=15)
            row = db.crisis_connector_health.find_one(
                {"org_id": org_id, "vendor": "crowdstrike"})
            assert row.get("quiet_alerted_at") is None, "new event should reset quiet_alerted_at"
        finally:
            sess.post(f"{BASE_URL}/api/crisis/settings",
                      json={"connector_quiet": False}, timeout=15)

    def test_run_quiet_alerts_opt_in_gated(self, sess):
        """With toggle off, run_connector_quiet_alerts returns 0 regardless of business hours."""
        sess.post(f"{BASE_URL}/api/crisis/settings",
                  json={"connector_quiet": False}, timeout=15)
        sys.path.insert(0, "/app/backend")
        for line in open("/app/backend/.env"):
            if "=" in line and not line.strip().startswith("#"):
                k, _, v = line.strip().partition("=")
                os.environ.setdefault(k, v.strip().strip('"').strip("'"))
        import importlib
        cc = importlib.import_module("crisis_commander")
        org_id = _org_id_for_email(ADMIN_EMAIL)
        alerted = _shared_loop().run_until_complete(cc.run_connector_quiet_alerts(org_id=org_id))
        assert alerted == 0


# ==========================
# Auth gating
# ==========================
class TestAuthGating:
    def test_settings_requires_auth(self):
        r = requests.get(f"{BASE_URL}/api/crisis/settings", timeout=10)
        assert r.status_code in (401, 403)

    def test_connector_test_requires_auth(self):
        r = requests.post(f"{BASE_URL}/api/crisis/connectors/crowdstrike/test", timeout=10)
        assert r.status_code in (401, 403)


# ==========================
# Helpers
# ==========================
def _mongo_db():
    sys.path.insert(0, "/app/backend")
    from pymongo import MongoClient
    url = os.environ.get("MONGO_URL")
    dbname = os.environ.get("DB_NAME")
    if not url:
        for line in open("/app/backend/.env"):
            k, _, v = line.strip().partition("=")
            if k == "MONGO_URL":
                url = v.strip().strip('"').strip("'")
            elif k == "DB_NAME":
                dbname = v.strip().strip('"').strip("'")
    return MongoClient(url)[dbname]


_SHARED_LOOP = None


def _shared_loop():
    global _SHARED_LOOP
    if _SHARED_LOOP is None or _SHARED_LOOP.is_closed():
        _SHARED_LOOP = asyncio.new_event_loop()
        asyncio.set_event_loop(_SHARED_LOOP)
    return _SHARED_LOOP


def _org_id_for_email(email: str) -> str:
    db = _mongo_db()
    u = db.users.find_one({"email": email})
    return str(u["org_id"]) if u else ""


def _delete_case_via_mongo(ref: str):
    try:
        db = _mongo_db()
        db.crisis_cases.delete_many({"ref": ref})
        db.crisis_events.delete_many({"case_ref": ref})
        db.crisis_snapshots.delete_many({"case_ref": ref})
        db.crisis_actions.delete_many({"case_ref": ref})
        db.crisis_participants.delete_many({"case_ref": ref})
        db.crisis_recovery.delete_many({"case_ref": ref})
        db.crisis_obligations.delete_many({"case_ref": ref})
    except Exception as e:
        print("cleanup failed:", e)
